[package]
name = "consensus_integrity"
version = "0.1.0"
edition = "2021"

[lib]
name = "consensus_integrity"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdi = "0.5.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
