[package]
name = "identity"
version = "0.1.0"
edition = "2021"

[lib]
name = "identity"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = "0.4.0"
identity_integrity = { path = "../identity_integrity" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
